export type Lang = "en" | "es";

export const translations = {
  en: {
    appName: "StanSsion",
    audio: "Audio",
    workspace: "Workspace",
    settings: "Settings",
    ambiente: "Ambiente",
    intensity: "Intensity",
    speed: "Speed",
    density: "Density",
    radio: "Radio",
    changeStation: "Change station",
    visualizer: "Visualizer",
    pomodoro: "Pomodoro",
    sleep: "Sleep",
    focus: "Focus",
    start: "Start",
    pause: "Pause",
    reset: "Reset",
    searchStations: "Search stations...",
    nowPlaying: "Now Playing",
    addToMixer: "Add to Mixer",
    favorites: "Favorites",
    getFullExperience: "Get the full experience",
    download: "Download StanSsion v1.0",
    appearance: "Appearance",
    performance: "Performance",
    data: "Data",
    comingSoon: "Coming soon",
    share: "Share",
    events: "Events",
    newEvent: "+ New event",
    scheduled: "Scheduled",
    saved: "Saved",
    noEventsYet: "No events yet — save your current mix as an event",
    noFavoritesYet: "No favorites yet — heart a station to save it",
    noCanvasYet: "Your canvas is empty — click a tool to start",
    eventName: "Event name",
    eventIcon: "Icon",
    eventTag: "Tag",
    withSchedule: "Schedule",
    save: "Save",
    cancel: "Cancel",
    allCountries: "All Countries",
    locationDetected: "Location detected: Colombia — showing local stations first",
    presets: "Presets",
    newPreset: "+ New preset",
    morningFocus: "Morning Focus",
    lateNight: "Late Night",
    deepWork: "Deep Work",
    play: "Play",
    audioSection: "Audio",
    synthQuality: "Ambient synthesis quality",
    radioBuffer: "Radio stream buffer",
    crossfade: "Crossfade duration",
    spatialAudio: "Enable spatial audio",
    normalization: "Master volume normalization",
    exportData: "Export all data",
    importBackup: "Import backup",
    clearEvents: "Clear events",
    clearCanvas: "Clear canvas data",
    clearFavorites: "Clear favorites",
    storageUsed: "Storage used",
    small: "Small (2s)",
    medium: "Medium (5s)",
    large: "Large (10s)",
    low: "Low",
    mediumQ: "Medium",
    high: "High",
    seconds: "sec",
    downloadApp: "Desktop App",
    areaDeTrabajoLabel: "Workspace",
    activeSession: "Active session · Rain + Radio Nacional CO",
    browseStations: "Browse Stations →",
    audioDashboard: "Audio Dashboard",
    workspaceCanvas: "Workspace Canvas",
    // Ambient type names
    ambRain: "Rain",
    ambStorm: "Storm",
    ambForest: "Forest",
    ambOcean: "Ocean",
    ambWind: "Wind",
    ambCafe: "Café",
    ambCave: "Cave",
    ambSpace: "Space",
    // Event param format
    eventParamSep: " · ",
    eventParamIntensity: (v: number) => `Intensity ${v}%`,
    eventParamTimer: (name: string, min: number) => `${name} ${min}m`,
    backToAudio: "← Back to Audio",
    // Custom timers
    timers: "Timers",
    newTimer: "+ New timer",
    timerName: "Timer name",
    timerDuration: "Duration (min)",
    deleteTimer: "Delete timer?",
    confirmDelete: "Yes",
    noTimers: "No timers — create one to get started",
    minTimerWarning: "At least one timer required",
    // Ambient configs
    saveAsConfig: "Save as config",
    configName: "Config name",
    noConfigs: "No saved configs yet",
    deleteConfig: "Remove",
    applyConfig: "Apply",
    // Playlist
    playlist: "Playlist",
    playlistWebTitle: "Playlist is available in the desktop app",
    playlistWebDesc: "Upload and manage your own MP3 files natively, without size limits or browser restrictions.",
    // Radio
    loadingStations: "Loading stations...",
    errorStations: "Could not load stations",
    retryStations: "Retry",
    detectingLocation: "Detecting your location...",
    allowLocation: "Allow location for local stations",
    noStationsFound: "No stations found",
    localStations: (country: string) => `Showing stations from ${country} first`,
    stationsCount: (n: number) => `${n} stations`,
    // Event delete
    deleteEvent: "Delete?",
    // ── Added in v5 ──────────────────────────────────────────
    all: "All",
    featured: "Featured",
    noFeatured: "No featured events — tap the star ★ on any event",
    color: "Color",
    addCustomSound: "Add custom sound",
    customSoundName: "Sound name",
    uploadAudioFile: "Upload audio (MP3 / WAV)",
    builtIn: "Built-in",
    deleteSound: "Delete sound?",
    chooseSound: "Choose ambient",
    // Workspace tools
    toolSelect: "Select / Pan",
    toolNote: "Note",
    toolTask: "Task list",
    toolImage: "Image",
    toolConnect: "Connect",
    disconnect: "Disconnect",
    exportBoard: "Export board",
    importBoard: "Import board",
    fitView: "Fit to view",
    addImageHint: "Click canvas to place, or paste an image (Ctrl+V)",
    canvasHint: "Note/Task tool: click empty canvas to create · Select tool: drag empty space to pan",
    // Settings — background & audio
    background: "Background",
    customColor: "Custom color",
    masterVolume: "Master volume",
    normalizeOutput: "Normalize output (limiter)",
    smoothCrossfade: "Smooth crossfade when switching",
    reduceMotionHint: "On = motion and transitions enabled · Off = disabled",
    importData: "Import backup",
    exportIncludesLabel: "Includes events, timers, ambient configs, canvas, favorites & settings",
    importConfirm: "This will overwrite current data. Continue?",
    cleared: "Cleared",
    // Radio (Radio Browser)
    radioByLocation: "Near you",
    radioTop: "Popular",
    radioSearchName: "Search by station name…",
    radioSearchCountry: "Filter by country…",
    detectingNear: "Finding stations near you…",
    couldNotDetect: "Couldn't detect location — showing popular stations",
    streamBlocked: "This stream could not be played (it may be offline or insecure)",
    // Timer
    timerLabel: "Timer",
    // ── v5.1 ──────────────────────────────────────────────────
    navDashboard: "Dashboard",
    navStations: "Stations",
    installDesktop: "Install desktop app",
    installSoonHint: "Coming soon",
    timerDone: "Time's up!",
    timerPresets: "Timers",
    newTimerShort: "New",
    playlists: "Playlists",
    newPlaylist: "New playlist",
    playlistName: "Playlist name",
    addToPlaylist: "Add to playlist",
    removeFromList: "Remove from list",
    emptyPlaylist: "Empty — add stations here",
    emptyMusicPlaylist: "Empty — add tracks here",
    shuffle: "Shuffle",
    favoritesTab: "Favorites",
    allTab: "All",
    storageReal: "Real usage (incl. audio)",
    notifBody: (name: string) => `${name} finished`,
    apiName: "Radio Browser API",
    radioSearchAny: "Search name, country or genre…",
    radioLimitsTitle: "About this radio source",
    radioLimits: [
      "Community database (Radio Browser) — not official; coverage varies by country.",
      "Results are capped (~120) and sorted by popularity, so not every station appears.",
      "http stations get blocked by the browser on https — they may not play.",
      "“Near you” uses your IP location; a VPN can change the detected country.",
      "Search works by name, country (English or Spanish) or genre.",
    ],
    storageMeta: "metadata in this browser",
    search: "Search…",
    noMatches: "No matches",
    spaceHelpTitle: "How storage works",
    spaceHelp: [
      "Audio you upload is saved in this browser, not in the cloud.",
      "Files can be large and count toward “Real usage” in Settings.",
      "They stay saved after you close the app, until you delete them.",
      "Use “Clear all” to free up space.",
    ],
    clearAll: "Clear all",
    clearAllConfirm: "Delete all uploaded audio? This frees space and can't be undone.",
  },
  es: {
    appName: "StanSsion",
    audio: "Audio",
    workspace: "Área de trabajo",
    settings: "Ajustes",
    ambiente: "Ambiente",
    intensity: "Intensidad",
    speed: "Velocidad",
    density: "Densidad",
    radio: "Radio",
    changeStation: "Cambiar emisora",
    visualizer: "Visualizador",
    pomodoro: "Pomodoro",
    sleep: "Sueño",
    focus: "Concentración",
    start: "Iniciar",
    pause: "Pausar",
    reset: "Reiniciar",
    searchStations: "Buscar emisoras...",
    nowPlaying: "Reproduciendo",
    addToMixer: "Agregar al mezclador",
    favorites: "Favoritos",
    getFullExperience: "Descarga la experiencia completa",
    download: "Descargar StanSsion v1.0",
    appearance: "Apariencia",
    performance: "Rendimiento",
    data: "Datos",
    comingSoon: "Próximamente",
    share: "Compartir",
    events: "Eventos",
    newEvent: "+ Nuevo evento",
    scheduled: "Programados",
    saved: "Guardados",
    noEventsYet: "Sin eventos — guarda tu mezcla actual como evento",
    noFavoritesYet: "Sin favoritos — marca una emisora para guardarla",
    noCanvasYet: "Tu lienzo está vacío — elige una herramienta para empezar",
    eventName: "Nombre del evento",
    eventIcon: "Ícono",
    eventTag: "Etiqueta",
    withSchedule: "Horario",
    save: "Guardar",
    cancel: "Cancelar",
    allCountries: "Todos los países",
    locationDetected: "Ubicación detectada: Colombia — mostrando emisoras locales primero",
    presets: "Presets",
    newPreset: "+ Nuevo preset",
    morningFocus: "Mañana enfocada",
    lateNight: "Noche tardía",
    deepWork: "Trabajo profundo",
    play: "Reproducir",
    audioSection: "Audio",
    synthQuality: "Calidad de síntesis ambiental",
    radioBuffer: "Buffer de transmisión",
    crossfade: "Duración de crossfade",
    spatialAudio: "Activar audio espacial",
    normalization: "Normalización de volumen",
    exportData: "Exportar todos los datos",
    importBackup: "Importar respaldo",
    clearEvents: "Borrar eventos",
    clearCanvas: "Borrar datos del lienzo",
    clearFavorites: "Borrar favoritos",
    storageUsed: "Almacenamiento usado",
    small: "Pequeño (2s)",
    medium: "Medio (5s)",
    large: "Grande (10s)",
    low: "Bajo",
    mediumQ: "Medio",
    high: "Alto",
    seconds: "seg",
    downloadApp: "Aplicación de escritorio",
    areaDeTrabajoLabel: "Área de trabajo",
    activeSession: "Sesión activa · Lluvia + Radio Nacional CO",
    browseStations: "Ver emisoras →",
    audioDashboard: "Panel de audio",
    workspaceCanvas: "Lienzo de trabajo",
    // Ambient type names
    ambRain: "Lluvia",
    ambStorm: "Tormenta",
    ambForest: "Bosque",
    ambOcean: "Océano",
    ambWind: "Viento",
    ambCafe: "Café",
    ambCave: "Cueva",
    ambSpace: "Espacio",
    // Event param format
    eventParamSep: " · ",
    eventParamIntensity: (v: number) => `Intensidad ${v}%`,
    eventParamTimer: (name: string, min: number) => `${name} ${min}m`,
    backToAudio: "← Volver al audio",
    // Custom timers
    timers: "Temporizadores",
    newTimer: "+ Nuevo temporizador",
    timerName: "Nombre",
    timerDuration: "Duración (min)",
    deleteTimer: "¿Eliminar?",
    confirmDelete: "Sí",
    noTimers: "Sin temporizadores — crea uno para empezar",
    minTimerWarning: "Se necesita al menos uno",
    // Ambient configs
    saveAsConfig: "Guardar config",
    configName: "Nombre de la config",
    noConfigs: "Sin configs guardadas",
    deleteConfig: "Eliminar",
    applyConfig: "Aplicar",
    // Playlist
    playlist: "Lista de reproducción",
    playlistWebTitle: "La lista de reproducción está disponible en la app de escritorio",
    playlistWebDesc: "Sube y gestiona tus archivos MP3 de forma nativa, sin límites de tamaño ni restricciones del navegador.",
    // Radio
    loadingStations: "Cargando emisoras...",
    errorStations: "No se pudieron cargar las emisoras",
    retryStations: "Reintentar",
    detectingLocation: "Detectando tu ubicación...",
    allowLocation: "Permitir ubicación para emisoras locales",
    noStationsFound: "No se encontraron emisoras",
    localStations: (country: string) => `Mostrando emisoras de ${country} primero`,
    stationsCount: (n: number) => `${n} emisoras`,
    // Event delete
    deleteEvent: "¿Eliminar?",
    // ── Added in v5 ──────────────────────────────────────────
    all: "Todos",
    featured: "Destacados",
    noFeatured: "Sin destacados — toca la estrella ★ en cualquier evento",
    color: "Color",
    addCustomSound: "Agregar sonido personalizado",
    customSoundName: "Nombre del sonido",
    uploadAudioFile: "Subir audio (MP3 / WAV)",
    builtIn: "Incluido",
    deleteSound: "¿Eliminar sonido?",
    chooseSound: "Elegir ambiente",
    // Workspace tools
    toolSelect: "Seleccionar / Mover",
    toolNote: "Nota",
    toolTask: "Lista de tareas",
    toolImage: "Imagen",
    toolConnect: "Conectar",
    disconnect: "Desconectar",
    exportBoard: "Exportar tablero",
    importBoard: "Importar tablero",
    fitView: "Ajustar a la vista",
    addImageHint: "Haz clic en el lienzo para colocar, o pega una imagen (Ctrl+V)",
    canvasHint: "Herramienta Nota/Tarea: clic en lienzo vacío para crear · Seleccionar: arrastra el vacío para mover",
    // Settings — background & audio
    background: "Fondo",
    customColor: "Color personalizado",
    masterVolume: "Volumen maestro",
    normalizeOutput: "Normalizar salida (limitador)",
    smoothCrossfade: "Transición suave al cambiar",
    reduceMotionHint: "Activado = movimiento y transiciones · Desactivado = sin animaciones",
    importData: "Importar respaldo",
    exportIncludesLabel: "Incluye eventos, temporizadores, configs de ambiente, lienzo, favoritos y ajustes",
    importConfirm: "Esto sobrescribirá los datos actuales. ¿Continuar?",
    cleared: "Borrado",
    // Radio (Radio Browser)
    radioByLocation: "Cerca de ti",
    radioTop: "Populares",
    radioSearchName: "Buscar por nombre de emisora…",
    radioSearchCountry: "Filtrar por país…",
    detectingNear: "Buscando emisoras cerca de ti…",
    couldNotDetect: "No se pudo detectar la ubicación — mostrando populares",
    streamBlocked: "No se pudo reproducir esta emisora (puede estar fuera de línea o ser insegura)",
    // Timer
    timerLabel: "Temporizador",
    // ── v5.1 ──────────────────────────────────────────────────
    navDashboard: "Dashboard",
    navStations: "Emisoras",
    installDesktop: "Instalar app de escritorio",
    installSoonHint: "Próximamente",
    timerDone: "¡Tiempo!",
    timerPresets: "Temporizadores",
    newTimerShort: "Nuevo",
    playlists: "Listas",
    newPlaylist: "Nueva lista",
    playlistName: "Nombre de la lista",
    addToPlaylist: "Agregar a lista",
    removeFromList: "Quitar de la lista",
    emptyPlaylist: "Vacía — agrega emisoras aquí",
    emptyMusicPlaylist: "Vacía — agrega canciones aquí",
    shuffle: "Aleatorio",
    favoritesTab: "Favoritas",
    allTab: "Todas",
    storageReal: "Uso real (incl. audio)",
    notifBody: (name: string) => `${name} terminó`,
    apiName: "Radio Browser API",
    radioSearchAny: "Buscar nombre, país o género…",
    radioLimitsTitle: "Sobre esta fuente de radio",
    radioLimits: [
      "Base comunitaria (Radio Browser): no es oficial y la cobertura varía por país.",
      "Los resultados tienen tope (~120) y se ordenan por popularidad, así que no salen todas.",
      "Las emisoras http las bloquea el navegador en https: pueden no sonar.",
      "“Cerca de ti” usa tu IP; con VPN puede cambiar el país detectado.",
      "La búsqueda funciona por nombre, país (español o inglés) o género.",
    ],
    storageMeta: "metadatos en este navegador",
    search: "Buscar…",
    noMatches: "Sin coincidencias",
    spaceHelpTitle: "Cómo funciona el espacio",
    spaceHelp: [
      "El audio que subís se guarda en este navegador, no en la nube.",
      "Los archivos pueden pesar y suman al “Uso real” de Ajustes.",
      "Quedan guardados aunque cierres la app, hasta que los borres.",
      "Usá “Borrar todo” para liberar espacio.",
    ],
    clearAll: "Borrar todo",
    clearAllConfirm: "¿Borrar todo el audio subido? Libera espacio y no se puede deshacer.",
  },
} as const;

export type Tr = typeof translations.en;
